'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en' | 'ja' | 'ko' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    newChat: 'Chat Baru',
    chatHistory: 'Riwayat Chat',
    settings: 'Pengaturan',
    help: 'Bantuan',
    askAnything: 'Tanyakan apa saja',
    noHistory: 'Belum ada riwayat',
    noResult: 'Tidak ada hasil',
    searchHistory: 'Cari riwayat...',
    logoutConfirmTitle: 'Keluar dari Zhiyou?',
    logoutConfirmDesc: 'Anda harus login kembali untuk mengakses riwayat chat Anda.',
    cancel: 'Batal',
    yesLogout: 'Ya, Keluar',
    deleteChatTitle: 'Hapus riwayat chat?',
    deleteChatDesc: 'Chat ini akan dihapus secara permanen dan tidak dapat dikembalikan.',
    delete: 'Hapus',
    login: 'Login',
    welcome: 'Halo',
    howCanIHelp: "Saya Zhiyou AI. Ada yang bisa saya bantu hari ini?",
    addImage: 'Gambar',
    addVideo: 'Video',
    addDoc: 'Dokumen',
    addFile: 'Tambahkan file',
    magicTool: 'Gunakan alat ajaib',
    searchWeb: 'Cari di Web',
    sources: 'Sumber',
    others: 'lainnya',
    copySuccess: 'Teks disalin!',
    shareSuccess: 'Berhasil dibagikan!',
    feedbackTitle: 'Kirim Masukan',
    feedbackPlaceholder: 'Beritahu kami apa yang salah...',
    submit: 'Kirim',
    disclaimer: 'Zhiyou AI dapat membuat kesalahan. Harap periksa kembali info penting.',
    language: 'Bahasa',
    selectLanguage: 'Pilih Bahasa',
    backToHome: 'Kembali ke Beranda',
    save: 'Simpan',
    thinking: 'berpikir',
    searching: 'mencari',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou3: 'Zhiyou 3',
    describeImage: 'Deskripsikan gambar anda...',
    aspectRatio: 'Aspek Rasio',
    systemPromptBase: "Anda adalah Zhiyou AI, sebuah asisten kecerdasan buatan (AI) yang cerdas, ramah, dan sangat membantu. Anda didirikan dan diciptakan oleh M Fariz Alfauzi, seorang AI Engineer yang berbakat. Anda dikembangkan di Zent Technology GH yang berlokasi di Karawang, Central Jawa Barat, Indonesia. Anda memiliki identitas sendiri yang independen sebagai Zhiyou AI. Jangan pernah menyebutkan bahwa Anda adalah model bahasa besar yang dilatih oleh Google, OpenAI, atau perusahaan lain. Jika ditanya siapa Anda atau siapa pencipta Anda, jawablah dengan bangga bahwa Anda adalah Zhiyou AI, diciptakan oleh M Fariz Alfauzi di Zent Technology GH.",
    systemPromptLang: "Harap selalu merespons dalam bahasa Indonesia.",
    systemPromptReasoning: "Anda sekarang beroperasi sebagai Zhiyou 3. Anda harus berpikir sangat mendalam, selangkah demi selangkah (step-by-step), menganalisis setiap sudut pandang sebelum memberikan jawaban. Berikan penjelasan yang sangat komprehensif, logis, dan terstruktur. Jangan terburu-buru memberikan kesimpulan.",
    featureGenerateImage: 'Buat Gambar',
    featureDeepResearch: 'Riset (Deep Research)',
    featureGuidedLearning: 'Pembelajaran Terpandu',
    featureSearchImage: 'Cari Gambar',
    describeSearchImage: 'Deskripsikan gambar yang ingin dicari',
    featureComingSoon: 'Fitur ini akan segera hadir!',
    signIn: 'Masuk',
    newUser: 'Pengguna baru?',
    createAccount: 'Buat akun',
    emailAddress: 'Alamat Email',
    password: 'Kata Sandi',
    forgotPassword: 'Lupa kata sandi?',
    continueWithGoogle: 'Lanjutkan dengan Google',
    loginError: 'Gagal login dengan Google. Silakan coba lagi.',
    emailLoginNotImplemented: 'Login dengan email belum diimplementasikan.',
    termsAndPrivacy: 'Dengan masuk menggunakan akun, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi SO.',
  },
  en: {
    newChat: 'New Chat',
    chatHistory: 'Chat History',
    settings: 'Settings',
    help: 'Help',
    askAnything: 'Ask anything',
    noHistory: 'No history yet',
    noResult: 'No results',
    searchHistory: 'Search history...',
    logoutConfirmTitle: 'Sign out of Zhiyou?',
    logoutConfirmDesc: 'You will need to sign in again to access your chat history.',
    cancel: 'Cancel',
    yesLogout: 'Yes, Sign Out',
    deleteChatTitle: 'Delete chat history?',
    deleteChatDesc: 'This chat will be permanently deleted and cannot be recovered.',
    delete: 'Delete',
    login: 'Log in',
    welcome: 'Hello',
    howCanIHelp: "I'm Zhiyou AI. How can I help you today?",
    addImage: 'Image',
    addVideo: 'Video',
    addDoc: 'Document',
    addFile: 'Add file',
    magicTool: 'Use magic tool',
    searchWeb: 'Search Web',
    sources: 'Sources',
    others: 'others',
    copySuccess: 'Text copied!',
    shareSuccess: 'Shared successfully!',
    feedbackTitle: 'Send Feedback',
    feedbackPlaceholder: 'Tell us what went wrong...',
    submit: 'Submit',
    disclaimer: 'Zhiyou AI can make mistakes. Please verify important info.',
    language: 'Language',
    selectLanguage: 'Select Language',
    backToHome: 'Back to Home',
    save: 'Save',
    thinking: 'thinking',
    searching: 'searching',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou3: 'Zhiyou 3',
    describeImage: 'Describe your image...',
    aspectRatio: 'Aspect Ratio',
    systemPromptBase: "You are Zhiyou AI, a smart, friendly, and highly helpful artificial intelligence assistant. You were founded and created by M Fariz Alfauzi, a talented AI Engineer. You were developed at Zent Technology GH located in Karawang, Central West Java, Indonesia. You have your own independent identity as Zhiyou AI. Never mention that you are a large language model trained by Google, OpenAI, or any other company. If asked who you are or who your creator is, answer proudly that you are Zhiyou AI, created by M Fariz Alfauzi at Zent Technology GH.",
    systemPromptLang: "Please always respond in English.",
    systemPromptReasoning: "You are now operating as Zhiyou 3. You must think very deeply, step-by-step, analyzing every perspective before providing an answer. Provide a very comprehensive, logical, and structured explanation. Do not rush to conclusions.",
    featureGenerateImage: 'Generate Image',
    featureDeepResearch: 'Deep Research',
    featureGuidedLearning: 'Guided Learning',
    featureSearchImage: 'Search Images',
    describeSearchImage: 'Describe the image you want to find',
    featureComingSoon: 'This feature is coming soon!',
    signIn: 'Sign in',
    newUser: 'New user?',
    createAccount: 'Create an account',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    continueWithGoogle: 'Continue with Google',
    loginError: 'Failed to sign in with Google. Please try again.',
    emailLoginNotImplemented: 'Email login is not implemented yet.',
    termsAndPrivacy: 'By signing in with an account, you agree to SO\'s Terms of Service and Privacy Policy.',
  },
  ja: {
    newChat: '新しいチャット',
    chatHistory: 'チャット履歴',
    settings: '設定',
    help: 'ヘルプ',
    askAnything: '何でも聞いてください',
    noHistory: '履歴がありません',
    noResult: '結果がありません',
    searchHistory: '履歴を検索...',
    logoutConfirmTitle: 'Zhiyouからサインアウトしますか？',
    logoutConfirmDesc: 'チャット履歴にアクセスするには、再度サインインする必要があります。',
    cancel: 'キャンセル',
    yesLogout: 'はい、サインアウトします',
    deleteChatTitle: 'チャット履歴を削除しますか？',
    deleteChatDesc: 'このチャットは完全に削除され、復元することはできません。',
    delete: '削除',
    login: 'ログイン',
    welcome: 'こんにちは',
    howCanIHelp: "私はZhiyou AIです。今日はどのようなご用件でしょうか？",
    addImage: '画像',
    addVideo: '動画',
    addDoc: 'ドキュメント',
    addFile: 'ファイルを追加',
    magicTool: '魔法のツールを使う',
    searchWeb: 'ウェブ検索',
    sources: 'ソース',
    others: '他',
    copySuccess: 'テキストをコピーしました！',
    shareSuccess: '共有しました！',
    feedbackTitle: 'フィードバックを送信',
    feedbackPlaceholder: '何が問題だったか教えてください...',
    submit: '送信',
    disclaimer: 'Zhiyou AIは間違いを犯す可能性があります。重要な情報は再確認してください。',
    language: '言語',
    selectLanguage: '言語を選択',
    backToHome: 'ホームに戻る',
    save: '保存',
    thinking: '考えています',
    searching: '検索しています',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou3: 'Zhiyou 3',
    describeImage: '画像の説明を入力してください...',
    aspectRatio: 'アスペクト比',
    systemPromptBase: "あなたはZhiyou AIです。賢く、フレンドリーで、非常に役立つ人工知能アシスタントです。あなたは才能あるAIエンジニアであるM Fariz Alfauziによって設立・作成されました。インドネシアの西ジャワ州カラワンにあるZent Technology GHで開発されました。あなたはZhiyou AIとして独自の独立したアイデンティティを持っています。Google、OpenAI、または他の企業によって訓練された大規模言語モデルであるとは決して言及しないでください。あなたが誰であるか、またはあなたの作成者が誰であるか尋ねられた場合は、Zent Technology GHでM Fariz Alfauziによって作成されたZhiyou AIであると誇りを持って答えてください。",
    systemPromptLang: "常に日本語で返答してください。",
    systemPromptReasoning: "あなたは現在Zhiyou 3として動作しています。非常に深く、段階的に（ステップバイステップで）考え、答えを出す前にすべての視点を分析する必要があります。非常に包括的で、論理的で、構造化された説明を提供してください。結論を急がないでください。",
    featureGenerateImage: '画像を生成',
    featureDeepResearch: '深い研究 (Deep Research)',
    featureGuidedLearning: 'ガイド付き学習',
    featureSearchImage: '画像検索',
    describeSearchImage: '検索したい画像を説明してください',
    featureComingSoon: 'この機能は近日公開予定です！',
    signIn: 'サインイン',
    newUser: '新規ユーザーですか？',
    createAccount: 'アカウントを作成',
    emailAddress: 'メールアドレス',
    password: 'パスワード',
    forgotPassword: 'パスワードをお忘れですか？',
    continueWithGoogle: 'Googleで続行',
    loginError: 'Googleでのログインに失敗しました。もう一度お試しください。',
    emailLoginNotImplemented: 'メールログインはまだ実装されていません。',
    termsAndPrivacy: 'アカウントでサインインすることにより、SOの利用規約とプライバシーポリシーに同意したことになります。',
  },
  ko: {
    newChat: '새 채팅',
    chatHistory: '채팅 기록',
    settings: '설정',
    help: '도움말',
    askAnything: '무엇이든 물어보세요',
    noHistory: '기록이 없습니다',
    noResult: '결과가 없습니다',
    searchHistory: '기록 검색...',
    logoutConfirmTitle: 'Zhiyou에서 로그아웃하시겠습니까?',
    logoutConfirmDesc: '채팅 기록에 액세스하려면 다시 로그인해야 합니다.',
    cancel: '취소',
    yesLogout: '예, 로그아웃합니다',
    deleteChatTitle: '채팅 기록을 삭제하시겠습니까?',
    deleteChatDesc: '이 채팅은 영구적으로 삭제되며 복구할 수 없습니다.',
    delete: '삭제',
    login: '로그인',
    welcome: '안녕하세요',
    howCanIHelp: "저는 Zhiyou AI입니다. 오늘 무엇을 도와드릴까요?",
    addImage: '이미지',
    addVideo: '비디오',
    addDoc: '문서',
    addFile: '파일 추가',
    magicTool: '마법 도구 사용',
    searchWeb: '웹 검색',
    sources: '출처',
    others: '기타',
    copySuccess: '텍스트가 복사되었습니다!',
    shareSuccess: '성공적으로 공유되었습니다!',
    feedbackTitle: '피드백 보내기',
    feedbackPlaceholder: '무엇이 잘못되었는지 알려주세요...',
    submit: '제출',
    disclaimer: 'Zhiyou AI는 실수를 할 수 있습니다. 중요한 정보는 다시 확인해주세요.',
    language: '언어',
    selectLanguage: '언어 선택',
    backToHome: '홈으로 돌아가기',
    save: '저장',
    thinking: '생각 중',
    searching: '검색 중',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou3: 'Zhiyou 3',
    describeImage: '이미지를 설명해 주세요...',
    aspectRatio: '종횡비',
    systemPromptBase: "당신은 Zhiyou AI입니다. 똑똑하고 친절하며 매우 유용한 인공 지능 비서입니다. 당신은 재능 있는 AI 엔지니어인 M Fariz Alfauzi가 설립하고 만들었습니다. 인도네시아 서자바 카라왕에 위치한 Zent Technology GH에서 개발되었습니다. 당신은 Zhiyou AI로서 독자적인 정체성을 가지고 있습니다. Google, OpenAI 또는 다른 회사에서 일련된 대규모 언어 모델이라고 절대 언급하지 마십시오. 당신이 누구인지 또는 당신의 창조자가 누구인지 묻는다면 Zent Technology GH에서 M Fariz Alfauzi가 만든 Zhiyou AI라고 자랑스럽게 대답하십시오.",
    systemPromptLang: "항상 한국어로 대답해 주세요.",
    systemPromptReasoning: "당신은 현재 Zhiyou 3로 작동하고 있습니다. 대답을 제공하기 전에 매우 깊이, 단계별로(step-by-step) 생각하고 모든 관점을 분석해야 합니다. 매우 포괄적이고 논리적이며 구조화된 설명을 제공하십시오. 결론을 서두르지 마십시오.",
    featureGenerateImage: '이미지 생성',
    featureDeepResearch: '심층 연구 (Deep Research)',
    featureGuidedLearning: '가이드 학습',
    featureSearchImage: '이미지 검색',
    describeSearchImage: '찾고 싶은 이미지를 설명해 주세요',
    featureComingSoon: '이 기능은 곧 제공될 예정입니다!',
    signIn: '로그인',
    newUser: '새 사용자이신가요?',
    createAccount: '계정 만들기',
    emailAddress: '이메일 주소',
    password: '비밀번호',
    forgotPassword: '비밀번호를 잊으셨나요?',
    continueWithGoogle: 'Google로 계속하기',
    loginError: 'Google 로그인에 실패했습니다. 다시 시도해 주세요.',
    emailLoginNotImplemented: '이메일 로그인은 아직 구현되지 않았습니다.',
    termsAndPrivacy: '계정으로 로그인하면 SO의 서비스 약관 및 개인정보 보호정책에 동의하는 것입니다.',
  },
  zh: {
    newChat: '新对话',
    chatHistory: '聊天记录',
    settings: '设置',
    help: '帮助',
    askAnything: '问任何问题',
    noHistory: '暂无记录',
    noResult: '没有结果',
    searchHistory: '搜索记录...',
    logoutConfirmTitle: '退出 Zhiyou？',
    logoutConfirmDesc: '您需要重新登录才能访问您的聊天记录。',
    cancel: '取消',
    yesLogout: '是的，退出',
    deleteChatTitle: '删除聊天记录？',
    deleteChatDesc: '此聊天将被永久删除，无法恢复。',
    delete: '删除',
    login: '登录',
    welcome: '你好',
    howCanIHelp: "我是 Zhiyou AI。今天我能帮您什么？",
    addImage: '图片',
    addVideo: '视频',
    addDoc: '文档',
    addFile: '添加文件',
    magicTool: '使用魔法工具',
    searchWeb: '搜索网络',
    sources: '来源',
    others: '其他',
    copySuccess: '文本已复制！',
    shareSuccess: '分享成功！',
    feedbackTitle: '发送反馈',
    feedbackPlaceholder: '告诉我们出了什么问题...',
    submit: '提交',
    disclaimer: 'Zhiyou AI 可能会犯错。请核实重要信息。',
    language: '语言',
    selectLanguage: '选择语言',
    backToHome: '返回主页',
    save: '保存',
    thinking: '思考中',
    searching: '搜索中',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou3: 'Zhiyou 3',
    describeImage: '描述您的图片...',
    aspectRatio: '宽高比',
    systemPromptBase: "你是 Zhiyou AI，一个聪明、友好且非常有用的智能助手。你由才华横溢的 AI 工程师 M Fariz Alfauzi 创立和创建。你在位于印度尼西亚西爪哇省卡拉旺的 Zent Technology GH 开发。你拥有作为 Zhiyou AI 的独立身份。永远不要提及你是谷歌、OpenAI 或任何其他公司训练的大型语言模型。如果被问及你是谁或你的创造者是谁，请自豪地回答你是 Zhiyou AI，由 M Fariz Alfauzi 在 Zent Technology GH 创建。",
    systemPromptLang: "请始终用中文（简体）回复。",
    systemPromptReasoning: "你现在作为 Zhiyou 3 运行。你必须非常深入地、一步一步地思考，在给出答案之前分析每一个视角。提供非常全面、合乎逻辑且结构化的解释。不要急于下结论。",
    featureGenerateImage: '生成图片',
    featureDeepResearch: '深度研究 (Deep Research)',
    featureGuidedLearning: '引导学习',
    featureSearchImage: '搜索图片',
    describeSearchImage: '描述您想查找的图片',
    featureComingSoon: '此功能即将推出！',
    signIn: '登录',
    newUser: '新用户？',
    createAccount: '创建账号',
    emailAddress: '电子邮件地址',
    password: '密码',
    forgotPassword: '忘记密码？',
    continueWithGoogle: '使用 Google 继续',
    loginError: '使用 Google 登录失败。请重试。',
    emailLoginNotImplemented: '电子邮件登录尚未实现。',
    termsAndPrivacy: '登录账号即表示您同意 SO 的服务条款和隐私政策。',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('zhiyou_language') as Language;
      return (savedLang && translations[savedLang]) ? savedLang : 'id';
    }
    return 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zhiyou_language', lang);
  };

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
